from enum import Enum


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class SignalStatus(str, Enum):
    WAITING_ENTRY = "WAITING_ENTRY"
    TRACKING = "TRACKING"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class TrackingStatus(str, Enum):
    WAITING_ENTRY = "WAITING_ENTRY"
    TRACKING = "TRACKING"
    CLOSED = "CLOSED"


class CloseReason(str, Enum):
    ORIGINAL_STOP_LOSS = "ORIGINAL_STOP_LOSS"
    MOVED_STOP_LOSS = "MOVED_STOP_LOSS"
    ALL_TARGETS_HIT = "ALL_TARGETS_HIT"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class MessageType(str, Enum):
    SIGNAL = "SIGNAL"

    TRACKING_STARTED = "TRACKING_STARTED"

    ENTRY1_HIT = "ENTRY1_HIT"
    ENTRY2_HIT = "ENTRY2_HIT"

    TARGET_HIT = "TARGET_HIT"

    SIGNAL_CANCELLED = "SIGNAL_CANCELLED"

    SIGNAL_CLOSED = "SIGNAL_CLOSED"

    DAILY_REPORT = "DAILY_REPORT"


class AuditEventType(str, Enum):
    SIGNAL_RECEIVED = "SIGNAL_RECEIVED"

    SIGNAL_REJECTED = "SIGNAL_REJECTED"

    SIGNAL_PUBLISHED = "SIGNAL_PUBLISHED"

    WAITING_FOR_ENTRY = "WAITING_FOR_ENTRY"

    TRACKING_STARTED = "TRACKING_STARTED"

    ENTRY1_HIT = "ENTRY1_HIT"

    ENTRY2_HIT = "ENTRY2_HIT"

    STOP_LOSS_MOVED = "STOP_LOSS_MOVED"

    TARGET_HIT = "TARGET_HIT"

    SIGNAL_CLOSED = "SIGNAL_CLOSED"

    SIGNAL_EXPIRED = "SIGNAL_EXPIRED"

    PROVIDER_SWITCHED = "PROVIDER_SWITCHED"

    ENGINE_RECOVERY = "ENGINE_RECOVERY"

    ERROR = "ERROR"


class Provider(str, Enum):
    BINANCE = "BINANCE"
    BYBIT = "BYBIT"
    OKX = "OKX"
