"""add_risk_free_tracking_fields

Revision ID: 23161b036e13
Revises: 799733a18324
Create Date: 2026-07-26 12:37:44.166142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23161b036e13'
down_revision: Union[str, Sequence[str], None] = '799733a18324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackings', sa.Column('peak_price_after_entry', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('trackings', sa.Column('halfway_to_tp1_reached', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackings', 'halfway_to_tp1_reached')
    op.drop_column('trackings', 'peak_price_after_entry')
    # ### end Alembic commands ###
