"""add telegram message queue table

Revision ID: 6a9fb9148cc5
Revises: 5efb75fcf94b
Create Date: 2026-08-16 11:58:37.529168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9fb9148cc5'
down_revision: Union[str, Sequence[str], None] = '5efb75fcf94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_message_queue',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reply_to', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('tracking_id', sa.Integer(), nullable=True),
    sa.Column('telegram_message_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_telegram_message_queue_signal_id_signals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracking_id'], ['trackings.id'], name=op.f('fk_telegram_message_queue_tracking_id_trackings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_message_queue'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_message_queue')
    # ### end Alembic commands ###
