"""add RISK_FREE enum and fix tracking Indexing

Revision ID: 799733a18324
Revises: f95bcfd8086f
Create Date: 2026-07-26 11:20:56.129139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799733a18324'
down_revision: Union[str, Sequence[str], None] = 'f95bcfd8086f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
