"""initial schema

Revision ID: 97df5f7ce412
Revises: 
Create Date: 2026-08-04 14:01:40.139092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97df5f7ce412'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('telegram_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('manual_priority', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_signals', sa.Integer(), nullable=False),
    sa.Column('winning_signals', sa.Integer(), nullable=False),
    sa.Column('losing_signals', sa.Integer(), nullable=False),
    sa.Column('cancelled_signals', sa.Integer(), nullable=False),
    sa.Column('expired_signals', sa.Integer(), nullable=False),
    sa.Column('average_profit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('average_tp', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('best_profit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('worst_profit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_sources')),
    sa.UniqueConstraint('telegram_username', name=op.f('uq_signal_sources_telegram_username'))
    )
    op.create_index(op.f('ix_signal_sources_is_active'), 'signal_sources', ['is_active'], unique=False)
    op.create_index(op.f('ix_signal_sources_parser_name'), 'signal_sources', ['parser_name'], unique=False)
    op.create_index(op.f('ix_signal_sources_score'), 'signal_sources', ['score'], unique=False)
    op.create_index(op.f('ix_signal_sources_telegram_channel_id'), 'signal_sources', ['telegram_channel_id'], unique=True)
    op.create_table('signals',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='direction_enum'), nullable=False),
    sa.Column('leverage', sa.SmallInteger(), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('WAITING_ENTRY', 'TRACKING', 'CLOSED', 'CANCELLED', 'EXPIRED', name='signal_status_enum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['signal_sources.id'], name=op.f('fk_signals_source_id_signal_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_expires_at'), 'signals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_signals_source_id'), 'signals', ['source_id'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('signal_entries',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_signal_entries_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_entries')),
    sa.UniqueConstraint('signal_id', 'position', name=op.f('uq_signal_entries_signal_id'))
    )
    op.create_index(op.f('ix_signal_entries_signal_id'), 'signal_entries', ['signal_id'], unique=False)
    op.create_table('signal_targets',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_signal_targets_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_targets')),
    sa.UniqueConstraint('signal_id', 'position', name=op.f('uq_signal_targets_signal_id'))
    )
    op.create_index(op.f('ix_signal_targets_signal_id'), 'signal_targets', ['signal_id'], unique=False)
    op.create_table('trackings',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING_ENTRY', 'TRACKING', 'RISK_FREE', 'CLOSED', 'CANCELLED', name='tracking_status_enum'), nullable=False),
    sa.Column('provider', sa.Enum('BINANCE', 'BYBIT', 'OKX', name='provider_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry1_touched', sa.Boolean(), nullable=False, comment='True when initial entry state reached: EntryHigh touched, startup past EntryHigh, or Emergency Entry. Does NOT necessarily mean EntryHigh price was physically touched - check entry_method to determine how entry occurred.'),
    sa.Column('entry2_touched', sa.Boolean(), nullable=False, comment='True only when EntryLow (averaging entry) was physically touched before any TP. Emergency Entry and startup never set this flag.'),
    sa.Column('actual_entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('entry_method', sa.Enum('ENTRY_1', 'EMERGENCY_ENTRY', name='entry_method_enum'), nullable=True),
    sa.Column('emergency_entry_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_tp1_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('current_stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('highest_target_hit', sa.SmallInteger(), nullable=False),
    sa.Column('close_reason', sa.Enum('ORIGINAL_STOP_LOSS', 'MOVED_STOP_LOSS', 'ALL_TARGETS_HIT', 'CANCELLED', 'EXPIRED', name='close_reason_enum'), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('profit_percent', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('peak_price_after_entry', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('halfway_to_tp1_reached', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_trackings_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trackings'))
    )
    op.create_index('ix_trackings_active', 'trackings', ['id'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index(op.f('ix_trackings_signal_id'), 'trackings', ['signal_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('tracking_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.Enum('SIGNAL_RECEIVED', 'SIGNAL_REJECTED', 'SIGNAL_PUBLISHED', 'WAITING_FOR_ENTRY', 'TRACKING_STARTED', 'ENTRY1_HIT', 'ENTRY2_HIT', 'EMERGENCY_ENTRY_HIT', 'TP1_RECALCULATED', 'STOP_LOSS_MOVED', 'TARGET_HIT', 'SIGNAL_CLOSED', 'SIGNAL_EXPIRED', 'PROVIDER_SWITCHED', 'ENGINE_RECOVERY', 'ERROR', name='audit_event_type_enum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_audit_logs_signal_id_signals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracking_id'], ['trackings.id'], name=op.f('fk_audit_logs_tracking_id_trackings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_signal_id'), 'audit_logs', ['signal_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tracking_id'), 'audit_logs', ['tracking_id'], unique=False)
    op.create_table('telegram_messages',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('SIGNAL', 'TRACKING_STARTED', 'ENTRY1_HIT', 'ENTRY2_HIT', 'TARGET_HIT', 'SIGNAL_CANCELLED', 'SIGNAL_CLOSED', 'DAILY_REPORT', name='message_type_enum'), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_telegram_messages_signal_id_signals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracking_id'], ['trackings.id'], name=op.f('fk_telegram_messages_tracking_id_trackings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_messages')),
    sa.UniqueConstraint('channel_id', 'message_id', name=op.f('uq_telegram_messages_channel_id'))
    )
    op.create_index(op.f('ix_telegram_messages_signal_id'), 'telegram_messages', ['signal_id'], unique=False)
    op.create_index(op.f('ix_telegram_messages_tracking_id'), 'telegram_messages', ['tracking_id'], unique=False)
    op.create_table('tp_hits',
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('profit_percent', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('hit_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracking_id'], ['trackings.id'], name=op.f('fk_tp_hits_tracking_id_trackings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tp_hits')),
    sa.UniqueConstraint('tracking_id', 'position', name=op.f('uq_tp_hits_tracking_id'))
    )
    op.create_index(op.f('ix_tp_hits_tracking_id'), 'tp_hits', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tp_hits_tracking_id'), table_name='tp_hits')
    op.drop_table('tp_hits')
    op.drop_index(op.f('ix_telegram_messages_tracking_id'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_signal_id'), table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_index(op.f('ix_audit_logs_tracking_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_signal_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_trackings_signal_id'), table_name='trackings')
    op.drop_index('ix_trackings_active', table_name='trackings', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('trackings')
    op.drop_index(op.f('ix_signal_targets_signal_id'), table_name='signal_targets')
    op.drop_table('signal_targets')
    op.drop_index(op.f('ix_signal_entries_signal_id'), table_name='signal_entries')
    op.drop_table('signal_entries')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_source_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_expires_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_signal_sources_telegram_channel_id'), table_name='signal_sources')
    op.drop_index(op.f('ix_signal_sources_score'), table_name='signal_sources')
    op.drop_index(op.f('ix_signal_sources_parser_name'), table_name='signal_sources')
    op.drop_index(op.f('ix_signal_sources_is_active'), table_name='signal_sources')
    op.drop_table('signal_sources')
    # ### end Alembic commands ###
