"""add_entry_price_field

Revision ID: efddebb5d50c
Revises: 23161b036e13
Create Date: 2026-07-26 12:59:33.374637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efddebb5d50c'
down_revision: Union[str, Sequence[str], None] = '23161b036e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackings', sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackings', 'entry_price')
    # ### end Alembic commands ###
